services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../Notebooks:/app/Notebooks
    restart: "on-failure"
    ports:
      - "8888:8888"

  selenium-hub:
    image: selenium/standalone-chrome:119.0
    #image: seleniarm/standalone-chromium:latest
    hostname: selenium-hub
    privileged: true
    shm_size: 2g
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=12
      - SE_VNC_NO_PASSWORD=1
    restart: always
    ports:
      - "4444:4444"
